package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.36

import (
	"context"
	"fmt"
	"slices"
	"strings"

	"github.com/99designs/gqlgen/graphql"
	"github.com/drew-harris/lapis/graph/model"
	"github.com/google/uuid"
)

// RegisterPlayer is the resolver for the registerPlayer field.
func (r *mutationResolver) RegisterPlayer(ctx context.Context, input model.NewPlayer) (*model.Player, error) {
	// Check if player already exists
	player := model.Player{}
	r.db.Where("name = ?", input.Name).First(&player)
	if player.ID != "" {
		return &player, nil
	}

	player = model.Player{
		ID:   uuid.New().String(),
		Name: input.Name,
	}

	result := r.db.Create(&player)
	if result.Error != nil {
		return nil, result.Error
	}
	return &player, nil
}

// Players is the resolver for the players field.
func (r *queryResolver) Players(ctx context.Context) ([]model.Player, error) {
	fields := graphql.CollectAllFields(ctx)
	fmt.Println(strings.Join(fields, " "))

	db := r.db

	if slices.Contains(fields, "logs") {
		fmt.Println("preloading logs")
		db = db.Preload("Logs")
	}
	players := []model.Player{}
	result := db.Find(&players)
	if result.Error != nil {
		return nil, result.Error
	}
	return players, nil
}

// Player is the resolver for the player field.
func (r *queryResolver) Player(ctx context.Context, id string) (*model.Player, error) {
	fields := graphql.CollectAllFields(ctx)
	player := model.Player{}
	fmt.Println(strings.Join(fields, " "))

	db := r.db

	if slices.Contains(fields, "logs") {
		fmt.Println("preloading logs")
		db = db.Preload("logs")
	}

	result := db.Where("id = ?", id).First(&player)
	if result.Error != nil {
		return nil, result.Error
	}
	return &player, nil
}
