package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.36

import (
	"context"
	"errors"
	"fmt"

	"github.com/drew-harris/lapis/graph/model"
	"github.com/google/uuid"
)

// Player is the resolver for the player field.
func (r *logResolver) Player(ctx context.Context, obj *model.Log) (*model.Player, error) {
	if obj.Player != nil {
		return obj.Player, nil // TODO: Fix weird memory error
	}
	fmt.Println("Using long query")
	player := model.Player{}
	r.db.Where("id = ?", obj.PlayerID).First(&player)
	if r.db.Error != nil {
		return nil, r.db.Error
	}
	return &player, nil
}

// CreatePlayer is the resolver for the createPlayer field.
func (r *mutationResolver) CreatePlayer(ctx context.Context, input model.NewPlayer) (*model.Player, error) {
	player := model.Player{
		ID:   uuid.New().String(),
		Name: input.Name,
	}
	result := r.db.Create(&player)
	if result.Error != nil {
		return nil, result.Error
	}
	return &player, nil
}

// Log is the resolver for the log field.
func (r *mutationResolver) Log(ctx context.Context, input model.LogInput) (*model.Log, error) {
	// Check if playerid is valid
	player := model.Player{}
	r.db.Where("id = ?", input.PlayerID).First(&player)
	if r.db.Error != nil {
		return nil, r.db.Error
	}
	if player.ID == "" {
		return nil, errors.New("Player id is not valid")
	}
	log := model.Log{
		ID:       uuid.New().String(),
		Message:  input.Message,
		PlayerID: input.PlayerID,
	}

	r.db.Create(&log)
	if r.db.Error != nil {
		return nil, r.db.Error
	}
	return &log, nil
}

// Logs is the resolver for the logs field.
func (r *playerResolver) Logs(ctx context.Context, obj *model.Player) ([]model.Log, error) {
	// Get the logs for a player
	logs := []model.Log{}
	r.db.Where("player_id = ?", obj.ID).Find(&logs)
	if r.db.Error != nil {
		return nil, r.db.Error
	}
	return logs, nil
}

// Logs is the resolver for the logs field.
func (r *queryResolver) Logs(ctx context.Context) ([]model.Log, error) {
	logs := []model.Log{}
	result := r.db.Preload("Player").Find(&logs) // TODO: Optimize this
	if result.Error != nil {
		return nil, result.Error
	}
	return logs, nil
}

// Log returns LogResolver implementation.
func (r *Resolver) Log() LogResolver { return &logResolver{r} }

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Player returns PlayerResolver implementation.
func (r *Resolver) Player() PlayerResolver { return &playerResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type logResolver struct{ *Resolver }
type mutationResolver struct{ *Resolver }
type playerResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
