// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type LogInput struct {
	Message    string                 `json:"message"`
	PlayerName string                 `json:"playerName"`
	Attributes map[string]interface{} `json:"attributes,omitempty"`
}

type NewPlayer struct {
	Name string `json:"name"`
}
