// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"fmt"
	"io"
	"strconv"
)

type InputPosition struct {
	Code           string                 `json:"code"`
	ObjectiveID    string                 `json:"objectiveID"`
	Unit           string                 `json:"unit"`
	AdditionalData map[string]interface{} `json:"additionalData,omitempty"`
}

type LimitFilter struct {
	Limit *int `json:"limit,omitempty"`
	Page  *int `json:"page,omitempty"`
}

type LogInput struct {
	Message    *string                `json:"message,omitempty"`
	Type       LogType                `json:"type"`
	PlayerName string                 `json:"playerName"`
	Attributes map[string]interface{} `json:"attributes,omitempty"`
}

type LogQueryFilter struct {
	PlayerID     *string   `json:"playerId,omitempty"`
	Type         []LogType `json:"type,omitempty"`
	HasAttribute *string   `json:"hasAttribute,omitempty"`
}

type NewCustomNode struct {
	Name       string                 `json:"name"`
	PlayerID   string                 `json:"playerId"`
	GraphData  map[string]interface{} `json:"graphData"`
	RecipeData map[string]interface{} `json:"recipeData"`
}

type NewPlayer struct {
	Name string  `json:"name"`
	ID   *string `json:"id,omitempty"`
}

type NewSave struct {
	Name      string                 `json:"name"`
	PlayerID  string                 `json:"playerId"`
	GraphData map[string]interface{} `json:"graphData"`
}

type LogType string

const (
	LogTypePlaceBlock     LogType = "PlaceBlock"
	LogTypeCollectItems   LogType = "CollectItems"
	LogTypeMFPFinishTask  LogType = "MFPFinishTask"
	LogTypeMFPGraphReview LogType = "MFPGraphReview"
)

var AllLogType = []LogType{
	LogTypePlaceBlock,
	LogTypeCollectItems,
	LogTypeMFPFinishTask,
	LogTypeMFPGraphReview,
}

func (e LogType) IsValid() bool {
	switch e {
	case LogTypePlaceBlock, LogTypeCollectItems, LogTypeMFPFinishTask, LogTypeMFPGraphReview:
		return true
	}
	return false
}

func (e LogType) String() string {
	return string(e)
}

func (e *LogType) UnmarshalGQL(v interface{}) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = LogType(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid LogType", str)
	}
	return nil
}

func (e LogType) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}
